ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS color TEXT DEFAULT '#2563eb';
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS start_time TIMESTAMPTZ;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS end_time TIMESTAMPTZ;